name = "MVC CSS"
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "MVC CSS - современный css паттерн"
homepage = "https://getdoks.org/"
tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
min_version = "0.75.0"

[author]
  name = "Henk Verlinde"
  homepage = "https://henkverlinde.com/"
